modified:   abstract-machine/Makefile 	new file:   abstract-machine/am/src/riscv/ysyxsoc/gpu.c 	new file:   abstract-machine/am/src/riscv/ysyxsoc/include/npc.h 	new file:   abstract-machine/am/src/riscv/ysyxsoc/include/ysyxsoc.h 	new file:   abstract-machine/am/src/riscv/ysyxsoc/ioe.c 	new file:   abstract-machine/am/src/riscv/ysyxsoc/keyboard.c 	new file:   abstract-machine/am/src/riscv/ysyxsoc/linker.ld 	new file:   abstract-machine/am/src/riscv/ysyxsoc/timer.c 	new file:   abstract-machine/am/src/riscv/ysyxsoc/trm.c 	new file:   abstract-machine/am/src/riscv/ysyxsoc/uart.c 	modified:   abstract-machine/klib/src/stdlib.c 	new file:   abstract-machine/scripts/platform/ysyxsoc.mk 	new file:   abstract-machine/scripts/riscv32e-ysyxsoc.mk 	modified:   nemu/Kconfig 	modified:   nemu/Makefile 	modified:   nemu/src/cpu/difftest/ref.c 	renamed:    nemu/src/isa/riscv32/ecall.c -> nemu/src/isa/riscv32/csr_control.c 	modified:   nemu/src/isa/riscv32/include/isa-def.h 	modified:   nemu/src/isa/riscv32/inst.c 	modified:   nemu/src/isa/riscv32/local-include/reg.h 	modified:   nemu/src/memory/paddr.c 	modified:   npc/.gitignore 	modified:   npc/Makefile 	modified:   npc/csrc/cpu/cpu.cpp 	modified:   npc/csrc/cpu/difftest.cpp 	modified:   npc/csrc/include/CPU.h 	deleted:    npc/csrc/include/DeviceIO.h 	modified:   npc/csrc/include/common.h 	modified:   npc/csrc/include/config.h 	modified:   npc/csrc/include/difftest.h 	deleted:    npc/csrc/include/mem.h 	modified:   npc/csrc/include/trace.h 	new file:   npc/csrc/main.cpp 	new file:   npc/csrc/memory/flash.cpp 	modified:   npc/csrc/memory/mem.cpp 	new file:   npc/csrc/memory/psram.cpp 	new file:   npc/csrc/memory/rom.cpp 	new file:   npc/csrc/memory/sdram.cpp 	renamed:    npc/csrc/devices/DeviceIO.cpp -> npc/csrc/mmio_devices/DeviceIO.cpp 	renamed:    npc/csrc/devices/Serial.cpp -> npc/csrc/mmio_devices/Serial.cpp 	renamed:    npc/csrc/devices/Timer.cpp -> npc/csrc/mmio_devices/Timer.cpp 	modified:   npc/csrc/sdb/sdb.cpp 	deleted:    npc/csrc/sim-main.cpp 	modified:   npc/csrc/trace/FST.cpp 	modified:   npc/csrc/trace/ftrace.cpp 	modified:   npc/csrc/trace/itrace.cpp 	new file:   npc/csrc/utils/performance_event.cpp 	new file:   npc/resource/Makefile 	new file:   npc/resource/char-test.c 	modified:   npc/src/main/scala/Elaborate.scala 	new file:   npc/src/main/scala/bus/AXI4IO.scala 	deleted:    npc/src/main/scala/bus/AXI4LiteIO.scala 	new file:   npc/src/main/scala/bus/Arbiter.scala 	deleted:    npc/src/main/scala/bus/MemArbiter.scala 	renamed:    npc/src/main/scala/bus/CLINT.scala -> npc/src/main/scala/bus/mockSoc/CLINT.scala 	renamed:    npc/src/main/scala/bus/MemExt.scala -> npc/src/main/scala/bus/mockSoc/MemExt.scala 	renamed:    npc/src/main/scala/bus/MemXbar.scala -> npc/src/main/scala/bus/mockSoc/MemXbar.scala 	renamed:    npc/src/main/scala/bus/UART.scala -> npc/src/main/scala/bus/mockSoc/UART.scala 	new file:   npc/src/main/scala/bus/mockSoc/ysyxSoCFull.scala 	deleted:    npc/src/main/scala/core/1_IFU.scala 	deleted:    npc/src/main/scala/core/2_IDU/Control.scala 	deleted:    npc/src/main/scala/core/2_IDU/InstDecoder.scala 	deleted:    npc/src/main/scala/core/3_EXU.scala 	deleted:    npc/src/main/scala/core/4_LSU.scala 	new file:   npc/src/main/scala/core/EXU.scala 	new file:   npc/src/main/scala/core/IDU/Control.scala 	new file:   npc/src/main/scala/core/IDU/InstDecoder.scala 	renamed:    npc/src/main/scala/core/2_IDU/RV32EInstr.scala -> npc/src/main/scala/core/IDU/RV32EInstr.scala 	new file:   npc/src/main/scala/core/IFU.scala 	new file:   npc/src/main/scala/core/LSU.scala 	renamed:    npc/src/main/scala/core/5_WBU.scala -> npc/src/main/scala/core/WBU.scala 	modified:   npc/src/main/scala/core/top.scala 	modified:   npc/src/main/scala/utils/DPICModule.scala 	modified:   npc/src/main/verilog/DPICModule.v 	deleted:    npc/src/main/verilog/InstFetchUnit.v 	modified:   npc/src/main/verilog/MemExt.v 	new file:   rt-thread-am 	modified:   ysyxSoC

diff --git a/npc/Makefile b/npc/Makefile
--- a/npc/Makefile
+++ b/npc/Makefile
@@ -1,15 +1,26 @@
 # ==============================================================================
 # 全局配置
 # ==============================================================================
-TOPNAME = ysyx_26010036
+TOPNAME = ysyxSoCFull
 BUILD_DIR = ./build
 OBJ_DIR = $(BUILD_DIR)/obj_dir
 BIN = $(BUILD_DIR)/$(TOPNAME)
+YSYXSOC_DIR = $(abspath ../ysyxSoC)
 
 YOSYS_STA_DIR ?= $(abspath ./yosys-sta)
 CLK_FREQ_MHZ ?= 500
 CLK_PORT_NAME ?= clock
 SDC_FILE ?= $(YOSYS_STA_DIR)/scripts/default.sdc
+
+# ==============================================================================
+# 切换流程：1、改变开关  2、改变ifu初始pc (如果开始difftest:用新配置编译nemu)
+# ==============================================================================
+USE_YSYXSOC ?= 1
+
+# NVBoard开关：当前仅支持开启soc时使用
+USE_NVBOARD ?= 0
+
+MOCKSOC_DIR = ./src/main/scala/bus/mockSoc
 
 .SECONDARY:
 -include ../Makefile
@@ -18,48 +29,72 @@ SDC_FILE ?= $(YOSYS_STA_DIR)/scripts/default.sdc
 # Chisel 构建 (Mill)
 # ==============================================================================
 
+ifeq ($(USE_YSYXSOC),1)
+
+verilog:
+	$(call git_commit, "generate verilog")
+	mkdir -p $(BUILD_DIR)
+	./mill -i runMain ElaborateSOC --target-dir $(BUILD_DIR)
+
+else
+
 verilog:
 	$(call git_commit, "generate verilog")
 	mkdir -p $(BUILD_DIR)
 	./mill -i runMain Elaborate --target-dir $(BUILD_DIR)
-	$(MAKE) strip_sv_loc
 
-test:
-	./mill -i test
-
-strip_sv_loc:
-	@echo "--- Stripping locator comments from $(BUILD_DIR)/*.sv ---"
-	@set -e; \
-	if [ -d "$(BUILD_DIR)" ]; then \
-	  find "$(BUILD_DIR)" -type f -name "*.sv" -print0 | \
-	    xargs -0 -r sed -i -E \
-	      -e '/^[[:space:]]*\/\/[[:space:]]*@/d' \
-	      -e 's|[[:space:]]*\/\/[[:space:]]*@.*$$||'; \
-	fi
-
-help:
-	./mill -i runMain Elaborate --help
-
-reformat:
-	./mill -i __.reformat
-
-checkformat:
-	./mill -i __.checkFormat
+endif
 
 clean:
 	-rm -rf $(BUILD_DIR)
 
-.PHONY: verilog help reformat checkformat clean
+.PHONY: verilog clean
+
+# ==============================================================================
+# NVBoard 接入
+# ==============================================================================
+ifeq ($(USE_NVBOARD),1)
+
+ifeq ($(NVBOARD_HOME),)
+$(error NVBOARD_HOME未设置，请先 export NVBOARD_HOME=<nvboard项目路径>)
+endif
+include $(NVBOARD_HOME)/scripts/nvboard.mk
+
+NXDC_FILES ?= $(abspath ./constr/$(TOPNAME).nxdc)
+
+SRC_AUTO_BIND = $(abspath $(BUILD_DIR)/auto_bind.cpp)
+$(SRC_AUTO_BIND): $(NXDC_FILES)
+	@mkdir -p $(dir $@)
+	python3 $(NVBOARD_HOME)/scripts/auto_pin_bind.py $^ $@
+
+
+endif
 
 # ==============================================================================
 # 源文件
 # ==============================================================================
 
-VSRCS = $(wildcard $(abspath $(BUILD_DIR))/*.v) \
-	$(wildcard $(abspath $(BUILD_DIR))/*.sv) \
-	$(shell find $(abspath ./src/main) \( -name "*.v" -o -name "*.sv" \))
+_BUILD_VSRCS = $(filter-out \
+  %/ysyxSoCFull.v %/ysyxSoCFull.sv, \
+  $(wildcard $(abspath $(BUILD_DIR))/*.v) \
+  $(wildcard $(abspath $(BUILD_DIR))/*.sv))
+
+VSRCS = \
+  $(_BUILD_VSRCS) \
+  $(shell find $(abspath ./src/main) \( -name "*.v" -o -name "*.sv" \))
+
+ifeq ($(USE_YSYXSOC),1)
+VSRCS += $(shell find $(YSYXSOC_DIR)/perip -name "*.v")
+VSRCS += $(YSYXSOC_DIR)/build/ysyxSoCFull.v
+else
+VSRCS += $(abspath $(BUILD_DIR)/ysyxSoCFull.sv)
+endif
 
 CSRCS = $(shell find $(abspath ./csrc) -name "*.c" -o -name "*.cc" -o -name "*.cpp")
+
+ifeq ($(USE_NVBOARD),1)
+CSRCS += $(SRC_AUTO_BIND)
+endif
 
 # ==============================================================================
 # Verilator 编译配置
@@ -70,10 +105,27 @@ VERILATOR_FLAGS += --cc --exe --build \
                    -o $(abspath $(BIN)) \
                    --top-module $(TOPNAME) \
                    -I$(abspath $(BUILD_DIR)/verification) \
-                   --trace-fst
+                   -I$(YSYXSOC_DIR)/perip/uart16550/rtl \
+                   -I$(YSYXSOC_DIR)/perip/spi/rtl \
+                   --timescale "1ns/1ns" \
+                   --no-timing \
+                   --trace-fst \
+                   --autoflush
+
+VERILATOR_FLAGS += -j $(shell nproc) \
+                   -O3 \
+                   --output-split 10000
+
+# VERILATOR_FLAGS += --threads 8
 
 VERILATOR_CFLAGS  += $(addprefix -CFLAGS , $(CXXFLAGS)) \
-                     $(addprefix -CFLAGS , -I$(abspath ./csrc))
+                     $(addprefix -CFLAGS , -I$(abspath ./csrc)) \
+                     -CFLAGS -DUSE_YSYXSOC=$(USE_YSYXSOC) \
+                     -CFLAGS -DUSE_NVBOARD=$(USE_NVBOARD)
+
+ifeq ($(USE_NVBOARD),1)
+VERILATOR_CFLAGS += $(addprefix -CFLAGS -I, $(INC_PATH))
+endif
 
 LDFLAGS           += -lreadline
 VERILATOR_LDFLAGS += $(addprefix -LDFLAGS , $(LDFLAGS))
@@ -86,7 +138,7 @@ default: sim
 
 vsim: verilog sim
 
-sim:
+sim: $(if $(filter 1,$(USE_NVBOARD)),$(NVBOARD_ARCHIVE) $(SRC_AUTO_BIND))
 	$(call git_commit, "sim RTL")
 	@echo "--- Building $(TOPNAME) with Verilator ---"
 	@mkdir -p $(OBJ_DIR)
@@ -94,32 +146,53 @@ sim:
 		echo "Error: No .v/.sv files found. Run 'make verilog' first."; \
 		exit 1; \
 	fi
-	verilator $(VERILATOR_FLAGS) $(VERILATOR_CFLAGS) $(VERILATOR_LDFLAGS) \
-		$(VSRCS) $(CSRCS)
+	verilator $(VERILATOR_FLAGS) \
+		$(VSRCS) $(CSRCS) $(if $(filter 1,$(USE_NVBOARD)),$(NVBOARD_ARCHIVE)) \
+		$(VERILATOR_CFLAGS) $(VERILATOR_LDFLAGS)
 	@echo "--- Running Simulation ---"
 	$(BIN) IMG=$(IMG) BUILD=$(BUILD_DIR)
-
+	
 rt: verilog
-	$(MAKE) -C /home/hy5un/Templates/rt-thread-am/bsp/abstract-machine run ARCH=riscv32e-npc
+	$(MAKE) -C /home/hy5un/ysyx-workbench/rt-thread-am/bsp/abstract-machine run \
+	  ARCH=$(if $(filter 1,$(USE_YSYXSOC)),riscv32e-ysyxsoc,riscv32e-npc)
+
+
+CORENAME = ysyx_26010036
 
 syn:
 	$(call git_commit, "run yosys synthesis")
 	@mkdir -p $(YOSYS_STA_DIR)/result
-	$(MAKE) -C $(YOSYS_STA_DIR) syn \
-		DESIGN=$(TOPNAME) \
+	@echo "=> Masking DPI-C modules..."
+	@python3 ./tools/mask_dpic.py mask $(VSRCS)
+	@echo "=> Running Synthesis..."
+	@if $(MAKE) -C $(YOSYS_STA_DIR) syn \
+		DESIGN=$(CORENAME) \
 		RTL_FILES="$(VSRCS)" \
 		CLK_FREQ_MHZ=$(CLK_FREQ_MHZ) \
 		CLK_PORT_NAME=$(CLK_PORT_NAME) \
-		SDC_FILE=$(abspath $(SDC_FILE))
+		SDC_FILE=$(abspath $(SDC_FILE)); then \
+		echo "=> Synthesis Success. Restoring RTL files..."; \
+		python3 ./tools/mask_dpic.py restore $(VSRCS); \
+	else \
+		echo "=> Synthesis Failed! Restoring RTL files..."; \
+		python3 ./tools/mask_dpic.py restore $(VSRCS); \
+		exit 1; \
+	fi
 
 sta:
 	$(call git_commit, "run yosys sta")
 	@mkdir -p $(YOSYS_STA_DIR)/result
 	$(MAKE) -C $(YOSYS_STA_DIR) sta \
-		DESIGN=$(TOPNAME) \
+		DESIGN=$(CORENAME) \
 		RTL_FILES="$(VSRCS)" \
 		CLK_FREQ_MHZ=$(CLK_FREQ_MHZ) \
 		CLK_PORT_NAME=$(CLK_PORT_NAME) \
 		SDC_FILE=$(abspath $(SDC_FILE))
 
-.PHONY: sim verilog test vsim rt syn sta strip_sv_loc
+perf:
+	$(MAKE) USE_YSYXSOC=0 verilog 
+	$(MAKE) USE_YSYXSOC=0 syn sta
+	$(MAKE) USE_YSYXSOC=1 verilog
+	$(MAKE) -C ../am-kernels/benchmarks/microbench run ARCH=riscv32e-ysyxsoc
+
+.PHONY: sim verilog test vsim rt syn sta perf
