> generate verilog ysyx_22040000 孙浩益 Linux LAPTOP-46P11TE0 6.6.87.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux  08:08:32 up 2 days, 18:51,  1 user,  load average: 0.54, 0.41, 0.41

diff --git a/npc/Makefile b/npc/Makefile
--- a/npc/Makefile
+++ b/npc/Makefile
@@ -135,16 +135,17 @@ vsim: verilog sim
 sim: $(if $(filter 1,$(USE_NVBOARD)),$(NVBOARD_ARCHIVE) $(SRC_AUTO_BIND))
 	$(call git_commit, "sim RTL")
 	@echo "--- Building $(TOPNAME) with Verilator ---"
-	@mkdir -p $(OBJ_DIR)
-	@if [ -z "$(VSRCS)" ]; then \
-		echo "Error: No .v/.sv files found. Run 'make verilog' first."; \
-		exit 1; \
-	fi
-	verilator $(VERILATOR_FLAGS) \
-		$(VSRCS) $(CSRCS) $(if $(filter 1,$(USE_NVBOARD)),$(NVBOARD_ARCHIVE)) \
-		$(VERILATOR_CFLAGS) $(VERILATOR_LDFLAGS)
-	@echo "--- Running Simulation ---"
-	$(BIN) IMG=$(IMG) BUILD=$(BUILD_DIR)
+	@echo $(INC_PATH)
+# 	@mkdir -p $(OBJ_DIR)
+# 	@if [ -z "$(VSRCS)" ]; then \
+# 		echo "Error: No .v/.sv files found. Run 'make verilog' first."; \
+# 		exit 1; \
+# 	fi
+# 	verilator $(VERILATOR_FLAGS) \
+# 		$(VSRCS) $(CSRCS) $(if $(filter 1,$(USE_NVBOARD)),$(NVBOARD_ARCHIVE)) \
+# 		$(VERILATOR_CFLAGS) $(VERILATOR_LDFLAGS)
+# 	@echo "--- Running Simulation ---"
+# 	$(BIN) IMG=$(IMG) BUILD=$(BUILD_DIR)
 	
 rt: verilog
 	$(MAKE) -C /home/hy5un/ysyx-workbench/rt-thread-am/bsp/abstract-machine run \
