> run yosys synthesis ysyx_22040000 孙浩益 Linux LAPTOP-46P11TE0 6.6.87.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux  12:21:27 up 13:00,  1 user,  load average: 0.30, 0.23, 0.20

diff --git a/npc/Makefile b/npc/Makefile
--- a/npc/Makefile
+++ b/npc/Makefile
@@ -181,12 +181,22 @@ rt: verilog
 syn:
 	$(call git_commit, "run yosys synthesis")
 	@mkdir -p $(YOSYS_STA_DIR)/result
-	$(MAKE) -C $(YOSYS_STA_DIR) syn \
+	@echo "=> Masking DPI-C modules..."
+	@python3 ./tools/mask_dpic.py mask $(VSRCS)
+	@echo "=> Running Synthesis..."
+	@if $(MAKE) -C $(YOSYS_STA_DIR) syn \
 		DESIGN=$(TOPNAME) \
 		RTL_FILES="$(VSRCS)" \
 		CLK_FREQ_MHZ=$(CLK_FREQ_MHZ) \
 		CLK_PORT_NAME=$(CLK_PORT_NAME) \
-		SDC_FILE=$(abspath $(SDC_FILE))
+		SDC_FILE=$(abspath $(SDC_FILE)); then \
+		echo "=> Synthesis Success. Restoring RTL files..."; \
+		python3 ./tools/mask_dpic.py restore $(VSRCS); \
+	else \
+		echo "=> Synthesis Failed! Restoring RTL files..."; \
+		python3 ./tools/mask_dpic.py restore $(VSRCS); \
+		exit 1; \
+	fi
 
 sta:
 	$(call git_commit, "run yosys sta")
